# Generated by Django 3.2.15 on 2023-02-08 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0002_imagelocation_imagingresult_imagingtype_labname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigationsimaging',
            name='imaging_location',
            field=models.ForeignKey(blank=True, db_column='imaging_location', null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_data.imagelocation'),
        ),
        migrations.AlterField(
            model_name='investigationsimaging',
            name='imaging_result',
            field=models.ForeignKey(blank=True, db_column='imaging_result', null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_data.imagingresult'),
        ),
        migrations.AlterField(
            model_name='investigationsimaging',
            name='imaging_type',
            field=models.ForeignKey(db_column='imaging_type', null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_data.imagingtype'),
        ),
        migrations.AlterField(
            model_name='investigationsimaging',
            name='lab_name',
            field=models.ForeignKey(blank=True, db_column='lab_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_data.labname'),
        ),
    ]
