# Generated by Django 3.2.15 on 2023-02-09 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0007_imagingtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationsimaging',
            name='imaging_type',
            field=models.ForeignKey(db_column='imaging_type', null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_data.imagingtype'),
        ),
    ]
