# Generated by Django 3.2.15 on 2023-02-09 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0008_investigationsimaging_imaging_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigationsimaging',
            name='imaging_type',
            field=models.ForeignKey(blank=True, db_column='imaging_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patient_data.imagingtype'),
        ),
    ]
