# Generated by Django 3.2.15 on 2023-02-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0010_prescription_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investigationspath',
            old_name='biopsy_type',
            new_name='path_type',
        ),
        migrations.AddField(
            model_name='investigationspath',
            name='guided_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
