# Generated by Django 3.2.15 on 2023-02-10 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient_data', '0011_auto_20230210_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigationslabs',
            name='normal_range',
        ),
        migrations.RemoveField(
            model_name='investigationslabs',
            name='tumor_marker_level',
        ),
        migrations.RemoveField(
            model_name='investigationslabs',
            name='tumor_marker_level_unit',
        ),
        migrations.RemoveField(
            model_name='investigationslabs',
            name='tumor_marker_name',
        ),
        migrations.RemoveField(
            model_name='investigationslabs',
            name='tumor_marker_normal_range',
        ),
        migrations.AddField(
            model_name='investigationslabs',
            name='normal_range_max',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investigationslabs',
            name='normal_range_min',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investigationspath',
            name='molecular_profile_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InvestigationsMolecular',
            fields=[
                ('mol_id', models.AutoField(primary_key=True, serialize=False)),
                ('mol_type', models.CharField(blank=True, max_length=255, null=True)),
                ('mol_result', models.CharField(blank=True, max_length=255, null=True)),
                ('mol_value', models.CharField(blank=True, max_length=255, null=True)),
                ('mol_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('lab_name', models.CharField(blank=True, max_length=255, null=True)),
                ('lab_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField()),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.CharField(blank=True, max_length=45, null=True)),
                ('parent_id', models.ForeignKey(db_column='parent_id', on_delete=django.db.models.deletion.CASCADE, to='patient_data.s1parentmain', to_field='crnumber')),
                ('s8_path_id', models.ForeignKey(db_column='s8_path_id', on_delete=django.db.models.deletion.CASCADE, to='patient_data.investigationspath')),
                ('user_id', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inv_molecular',
            },
        ),
    ]
