# Generated by Django 3.2.15 on 2023-02-10 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0012_auto_20230210_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigationspath',
            name='biopsy_result',
            field=models.ForeignKey(db_column='biopsy_result', null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_data.hpe'),
        ),
        migrations.AlterField(
            model_name='investigationspath',
            name='path_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
