# Generated by Django 3.2.15 on 2023-02-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0013_auto_20230210_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigationslabs',
            name='test_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='investigationslabs',
            name='test_result',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
