# Generated by Django 3.2.15 on 2023-02-10 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0015_auto_20230210_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigationsimaging',
            name='imaging_result',
            field=models.ForeignKey(db_column='imaging_result', null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_data.imagingresult'),
        ),
        migrations.AlterField(
            model_name='investigationsimaging',
            name='imaging_type',
            field=models.ForeignKey(db_column='imaging_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patient_data.imagingtype'),
        ),
    ]
