# Generated by Django 3.2.15 on 2023-02-10 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient_data', '0017_alter_prescription_symptoms'),
    ]

    operations = [
        migrations.CreateModel(
            name='LateToxicity',
            fields=[
                ('s8_latetox_id', models.AutoField(primary_key=True, serialize=False)),
                ('toxtype', models.CharField(max_length=255, null=True)),
                ('toxgrade', models.CharField(blank=True, max_length=255, null=True)),
                ('toxdetails', models.TextField()),
                ('drug_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dosage', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('route', models.CharField(blank=True, max_length=255, null=True)),
                ('frequency', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.CharField(blank=True, max_length=45, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('parent_id', models.ForeignKey(db_column='parent_id', on_delete=django.db.models.deletion.CASCADE, to='patient_data.s1parentmain', to_field='crnumber')),
                ('s8_id', models.ForeignKey(db_column='s8_id', on_delete=django.db.models.deletion.CASCADE, to='patient_data.s8fup')),
                ('user_id', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'late_toxicity',
            },
        ),
    ]
