# Generated by Django 3.2.15 on 2023-02-10 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0020_alter_investigationsmolecular_s8_path_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigationsmolecular',
            name='s8_path_id',
            field=models.ForeignKey(db_column='s8_path_id', on_delete=django.db.models.deletion.CASCADE, to='patient_data.investigationspath'),
        ),
        migrations.AlterField(
            model_name='investigationspath',
            name='s8_id',
            field=models.ForeignKey(db_column='s8_id', on_delete=django.db.models.deletion.DO_NOTHING, to='patient_data.s8fup'),
        ),
    ]
