# Generated by Django 3.2.15 on 2023-02-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0022_auto_20230210_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigationsmolecular',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investigationspath',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
