# Generated by Django 3.2.15 on 2023-02-11 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient_data', '0026_auto_20230211_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='S5ChemoProtocol',
            fields=[
                ('s5_protocol_id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.CharField(blank=True, max_length=45, null=True)),
                ('chemo_protocol', models.ForeignKey(blank=True, db_column='chemo_protocol', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patient_data.chemoprotocolnew')),
                ('parent_id', models.ForeignKey(db_column='parent_id', on_delete=django.db.models.deletion.CASCADE, to='patient_data.s1parentmain', to_field='crnumber')),
                ('s3_id', models.ForeignKey(db_column='s3_id', on_delete=django.db.models.deletion.CASCADE, to='patient_data.s3careplan')),
                ('unit', models.ForeignKey(blank=True, db_column='unit', null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_data.referredby', to_field='refby')),
                ('user_id', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 's5_child_cp_ch_protocol',
            },
        ),
        migrations.CreateModel(
            name='S5ChemoDrugs',
            fields=[
                ('ch_id', models.AutoField(primary_key=True, serialize=False)),
                ('cycleno', models.IntegerField(blank=True, null=True)),
                ('chemo_day', models.CharField(blank=True, max_length=45, null=True)),
                ('chemodate', models.DateTimeField(blank=True, null=True)),
                ('d1dose', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.CharField(blank=True, max_length=45, null=True)),
                ('drug', models.ForeignKey(db_column='drug', null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_data.chemodrugs')),
                ('parent_id', models.ForeignKey(db_column='parent_id', on_delete=django.db.models.deletion.CASCADE, to='patient_data.s1parentmain', to_field='crnumber')),
                ('s5_protocol_id', models.ForeignKey(db_column='s5_protocol_id', on_delete=django.db.models.deletion.CASCADE, to='patient_data.s5chemoprotocol')),
                ('user_id', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 's5_child_cp_ch_drugs',
            },
        ),
    ]
