# Generated by Django 3.2.15 on 2023-02-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0027_s5chemodrugs_s5chemoprotocol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='s5chemodrugs',
            old_name='d1dose',
            new_name='dose',
        ),
        migrations.AddField(
            model_name='s5chemodrugs',
            name='measuring_unit',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
