# Generated by Django 3.2.15 on 2023-02-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0029_s5chemoprotocol_protocol_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemodrugs',
            name='drug_class',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
