# Generated by Django 3.2.15 on 2023-02-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0030_chemodrugs_drug_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTCV5',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('system', models.CharField(max_length=255)),
                ('term', models.CharField(max_length=255)),
                ('grade0', models.CharField(blank=True, max_length=25, null=True)),
                ('grade1', models.CharField(blank=True, max_length=255, null=True)),
                ('grade2', models.CharField(blank=True, max_length=255, null=True)),
                ('grade3', models.CharField(blank=True, max_length=255, null=True)),
                ('grade4', models.CharField(blank=True, max_length=255, null=True)),
                ('grade5', models.CharField(blank=True, max_length=255, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ctc_v5_27_11_2017',
            },
        ),
    ]
