# Generated by Django 3.2.15 on 2023-02-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0031_ctcv5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctcv5',
            name='grade1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ctcv5',
            name='grade2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ctcv5',
            name='grade3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ctcv5',
            name='grade4',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
