# Generated by Django 3.2.15 on 2023-02-13 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient_data', '0032_auto_20230213_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctcv5',
            name='term',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='AcuteToxicity',
            fields=[
                ('s8_acutetox_id', models.AutoField(primary_key=True, serialize=False)),
                ('tox_system', models.CharField(blank=True, max_length=255, null=True)),
                ('tox_grade', models.TextField()),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_by', models.CharField(blank=True, max_length=45, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('parent_id', models.ForeignKey(db_column='parent_id', on_delete=django.db.models.deletion.CASCADE, to='patient_data.s1parentmain', to_field='crnumber')),
                ('s7_id', models.ForeignKey(db_column='s7_id', on_delete=django.db.models.deletion.CASCADE, to='patient_data.s7assessment')),
                ('tox_term', models.ForeignKey(db_column='tox_term', null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_data.ctcv5', to_field='term')),
                ('user_id', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'acute_toxicity',
            },
        ),
    ]
