# Generated by Django 3.2.15 on 2023-02-13 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0033_auto_20230213_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='s7_id',
            field=models.ForeignKey(blank=True, db_column='s7_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_data.s7assessment'),
        ),
    ]
