# Generated by Django 3.2.15 on 2023-02-13 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0034_prescription_s7_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='s8_id',
            field=models.ForeignKey(blank=True, db_column='s8_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_data.s8fup'),
        ),
    ]
