# Generated by Django 3.2.15 on 2023-02-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0041_rename_day1date_newpresimulation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpresimulation',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='newpresimulation',
            name='day',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
