# Generated by Django 3.2.15 on 2023-02-22 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0042_auto_20230220_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='presimid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patient_data.newpresimulation'),
        ),
    ]
