# Generated by Django 3.2.15 on 2023-03-22 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0044_alter_s4rt_simid'),
    ]

    operations = [
        migrations.AddField(
            model_name='s2diagnosis',
            name='p_m',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='path_m', to='patient_data.clinm'),
        ),
        migrations.AddField(
            model_name='s2diagnosis',
            name='p_n',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='path_n', to='patient_data.clinn'),
        ),
        migrations.AddField(
            model_name='s2diagnosis',
            name='p_stage_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='path_stage_group', to='patient_data.stagegroup'),
        ),
        migrations.AddField(
            model_name='s2diagnosis',
            name='p_t',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='path_t', to='patient_data.clint'),
        ),
        migrations.AlterField(
            model_name='s4rt',
            name='s3_id',
            field=models.ForeignKey(db_column='s3_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s4rt', to='patient_data.s3careplan'),
        ),
    ]
