# Generated by Django 3.2.15 on 2023-03-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0046_simulation_finalstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='finalstatus',
            field=models.IntegerField(blank=True, db_column='finalstatus', null=True),
        ),
    ]
