# Generated by Django 3.2.15 on 2023-04-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0050_grouptnm'),
    ]

    operations = [
        migrations.AddField(
            model_name='tnm',
            name='c_m1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
