# Generated by Django 3.2.15 on 2023-04-22 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0051_tnm_c_m1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tnm',
            old_name='p_m0_iplus',
            new_name='p_m1',
        ),
    ]
