# Generated by Django 3.2.15 on 2023-04-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0052_rename_p_m0_iplus_tnm_p_m1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnm',
            name='c_tx',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
