# Generated by Django 3.2.15 on 2023-04-22 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0056_auto_20230422_0741'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupTNM',
            new_name='BreastGroupTNM',
        ),
        migrations.AlterModelTable(
            name='breastgrouptnm',
            table='breast_tnm_group',
        ),
    ]
