# Generated by Django 3.2.15 on 2023-04-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0057_auto_20230422_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='STSGroupTNM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staging_type', models.CharField(max_length=100)),
                ('t', models.CharField(max_length=50)),
                ('n', models.CharField(max_length=50)),
                ('m', models.CharField(max_length=50)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('stage', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'sts_tnm_group',
            },
        ),
    ]
