# Generated by Django 3.2.15 on 2023-04-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0059_nsclcgrouptnm'),
    ]

    operations = [
        migrations.CreateModel(
            name='LarynxGroupTNM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staging_type', models.CharField(max_length=100)),
                ('t', models.CharField(max_length=50)),
                ('n', models.CharField(max_length=50)),
                ('m', models.CharField(max_length=50)),
                ('stage', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tnm_larynx_group',
            },
        ),
        migrations.CreateModel(
            name='NasoGroupTNM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staging_type', models.CharField(max_length=100)),
                ('t', models.CharField(max_length=50)),
                ('n', models.CharField(max_length=50)),
                ('m', models.CharField(max_length=50)),
                ('stage', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tnm_naso_group',
            },
        ),
        migrations.CreateModel(
            name='OralGroupTNM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staging_type', models.CharField(max_length=100)),
                ('t', models.CharField(max_length=50)),
                ('n', models.CharField(max_length=50)),
                ('m', models.CharField(max_length=50)),
                ('stage', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tnm_oral_group',
            },
        ),
        migrations.CreateModel(
            name='OroHpvNegGroupTNM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staging_type', models.CharField(max_length=100)),
                ('t', models.CharField(max_length=50)),
                ('n', models.CharField(max_length=50)),
                ('m', models.CharField(max_length=50)),
                ('stage', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tnm_orohypo_hpvneg_group',
            },
        ),
        migrations.CreateModel(
            name='OroHpvPosGroupTNM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staging_type', models.CharField(max_length=100)),
                ('t', models.CharField(max_length=50)),
                ('n', models.CharField(max_length=50)),
                ('m', models.CharField(max_length=50)),
                ('stage', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tnm_oro_hpvpos_group',
            },
        ),
        migrations.CreateModel(
            name='PNSGroupTNM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staging_type', models.CharField(max_length=100)),
                ('t', models.CharField(max_length=50)),
                ('n', models.CharField(max_length=50)),
                ('m', models.CharField(max_length=50)),
                ('stage', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tnm_pns_group',
            },
        ),
        migrations.AlterModelTable(
            name='breastgrouptnm',
            table='tnm_breast_group',
        ),
        migrations.AlterModelTable(
            name='nsclcgrouptnm',
            table='tnm_nsclc_group',
        ),
        migrations.AlterModelTable(
            name='stsgrouptnm',
            table='tnm_sts_group',
        ),
    ]
