# Generated by Django 3.2.15 on 2023-04-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0061_esogrouptnm'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenDrugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug', models.CharField(max_length=255, unique=True)),
                ('composition', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'gen_drugs',
            },
        ),
    ]
