# Generated by Django 3.2.15 on 2023-04-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0062_gendrugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gendrugs',
            name='composition',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
