# Generated by Django 3.2.15 on 2023-04-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0063_alter_gendrugs_composition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s7assessment',
            name='fxdone',
            field=models.IntegerField(null=True),
        ),
    ]
