# Generated by Django 3.2.15 on 2023-04-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0064_alter_s7assessment_fxdone'),
    ]

    operations = [
        migrations.AddField(
            model_name='s2diagnosis',
            name='m_new',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='s2diagnosis',
            name='n_new',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='s2diagnosis',
            name='stage_new',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='s2diagnosis',
            name='t_new',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
