# Generated by Django 3.2.15 on 2023-04-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0065_auto_20230424_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='s2diagnosis',
            name='P_m_new',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='s2diagnosis',
            name='p_n_new',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='s2diagnosis',
            name='p_stage_new',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='s2diagnosis',
            name='p_t_new',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
