# Generated by Django 3.2.15 on 2023-04-26 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0066_auto_20230425_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='s2diagnosis',
            old_name='P_m_new',
            new_name='p_m_new',
        ),
    ]
