# Generated by Django 3.2.15 on 2023-04-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0067_rename_p_m_new_s2diagnosis_p_m_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='s2diagnosis',
            name='mets_site',
            field=models.ManyToManyField(blank=True, related_name='mets_site', to='patient_data.FMAID'),
        ),
        migrations.AddField(
            model_name='s2diagnosis',
            name='p_mets_site',
            field=models.ManyToManyField(blank=True, related_name='p_mets_site', to='patient_data.FMAID'),
        ),
    ]
