# Generated by Django 3.2.15 on 2023-05-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0068_auto_20230426_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='RCCGroupTNM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staging_type', models.CharField(max_length=100)),
                ('t', models.CharField(max_length=50)),
                ('n', models.CharField(max_length=50)),
                ('m', models.CharField(max_length=50)),
                ('stage', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tnm_rcc_group',
            },
        ),
    ]
