# Generated by Django 3.2.15 on 2023-05-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_data', '0069_rccgrouptnm'),
    ]

    operations = [
        migrations.AddField(
            model_name='s7assessment',
            name='next_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
