from django.contrib import admin
from .models import City, Comorbidity, Referredby, OurDiagnosis, HPE, Site, ChemoProtocolNew, FollowupVisitsType, \
    FollowupActions, StrType, StrName, StrNameClassifierBase, StrNameClassifierNumber, StrNameClassifierImage, \
    StrNameClassifierDose, StrNameClassifierCustom, DVHParameters, RTSites, ICDMainSites, RTTech, RTIntent, RTVolumes, \
    PreSimStatus, SimStatus, DxType, BiopsyGrade, ClinT, ClinN, ClinM, StageGroup, AjccEdition, StudyGroup, \
    RTMachines, RTStatus, ChemoDrugs, SxCodes, FMAID, ImagingType, ImageLocation, ImagingResult, LabName, CTCV5, TNM, \
    BreastGroupTNM, NSCLCGroupTNM, OralGroupTNM, NasoGroupTNM, OroHpvNegGroupTNM, OroHpvPosGroupTNM, LarynxGroupTNM, \
    PNSGroupTNM, EsoGroupTNM, GenDrugs

admin.site.register(City)
admin.site.register(Comorbidity)
admin.site.register(Referredby)
admin.site.register(OurDiagnosis)
admin.site.register(HPE)
admin.site.register(Site)
admin.site.register(ChemoProtocolNew)
admin.site.register(FollowupVisitsType)
admin.site.register(FollowupActions)
admin.site.register(StrType)
admin.site.register(StrName)
admin.site.register(StrNameClassifierBase)
admin.site.register(StrNameClassifierNumber)
admin.site.register(StrNameClassifierImage)
admin.site.register(StrNameClassifierDose)
admin.site.register(StrNameClassifierCustom)
admin.site.register(DVHParameters)
admin.site.register(RTSites)
admin.site.register(ICDMainSites)
admin.site.register(RTTech)
admin.site.register(RTIntent)
admin.site.register(RTVolumes)
admin.site.register(PreSimStatus)
admin.site.register(SimStatus)
admin.site.register(DxType)
admin.site.register(BiopsyGrade)
admin.site.register(ClinT)
admin.site.register(ClinN)
admin.site.register(ClinM)
admin.site.register(StageGroup)
admin.site.register(AjccEdition)
admin.site.register(StudyGroup)
admin.site.register(RTMachines)
admin.site.register(RTStatus)
admin.site.register(ChemoDrugs)
admin.site.register(SxCodes)
admin.site.register(FMAID)
admin.site.register(ImagingType)
admin.site.register(ImageLocation)
admin.site.register(ImagingResult)
admin.site.register(LabName)
admin.site.register(CTCV5)
admin.site.register(TNM)
admin.site.register(BreastGroupTNM)
admin.site.register(NSCLCGroupTNM)
admin.site.register(OralGroupTNM)
admin.site.register(NasoGroupTNM)
admin.site.register(OroHpvNegGroupTNM)
admin.site.register(OroHpvPosGroupTNM)
admin.site.register(LarynxGroupTNM)
admin.site.register(PNSGroupTNM)
admin.site.register(EsoGroupTNM)
admin.site.register(GenDrugs)
